name: 'generate-license-report'
author: 'Dafnik'
description: 'Generates a license report'
branding:
  icon: 'grid'
  color: 'purple'

inputs:
  package-json-path:
    description: 'package.json path'
    required: false
    default: 'package.json'
  license-report-path:
    description: 'file path'
    required: false
    default: 'licenses.json'
  output-format:
    description: 'output format'
    required: false
    default: 'json'

runs:
  using: 'node16'
  main: 'dist/index.js'
