name: test
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
        pnpm: [7, 8]
    steps:
      - uses: actions/checkout@v3

      # Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile --ignore-scripts

      - uses: ./
