name: test
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
        pnpm: [7, 8]
    steps:
      - uses: actions/checkout@v3
      - uses: dafnik/setup-node-pnpm@v1
        with:
          node: ${{ matrix.node }}
          pnpm: ${{ matrix.pnpm }}
          install-ignore-scripts: true
      - uses: ./
